INSERT INTO `settings` (`id`, `name`, `value`, `type`, `module`, `order_by`) VALUES
(NULL, 'appName', 'نظام تجريبي', 'text', 'main', '0'),
(NULL, 'appLogo', 'appLogo.png', 'file', 'main', '0'),
(NULL, 'appDesc', 'وصف نظام تجريبي', 'textarea', 'main', '0'),
(NULL, 'copyright', 'جميع الحقوق محفوظه لنظام تجريبي', 'text', 'main', '0'),
(NULL, 'defaultLocal', 'ar', 'text', 'main', '0'),
(NULL, 'generalShippingPrice', '20', 'text', 'main', '0'),
(NULL, 'status', '1', 'select', 'main', '0'),
(NULL, 'closeMsg', 'النظام مغلق', 'textarea', 'main', '0'),
(NULL, 'facebook', 'https://www.fb.com', 'text', 'social', '0'),
(NULL, 'twitter', 'https://www.twitter.com', 'text', 'social', '0'),
(NULL, 'google', 'www.google.com', 'text', 'social', '0'),
(NULL, 'instagram', 'https://www.instagram.com', 'text', 'social', '0'),
(NULL, 'linkedin', 'www.linkedin.com', 'text', 'social', '0'),
(NULL, 'whatsApp', '01000000000', 'text', 'social', '0'),
(NULL, 'phone', '01053651178', 'text', 'main', '0'),
(NULL, 'email', 'email@ejjadh.com', 'text', 'main', '0'),
(NULL, 'address', 'مدينة المنصوره شارع  قناة السويس', 'text', 'main', '0');
(NULL, 'defaultCurrency', 'SAR', 'text', 'main', '0'),
